### PR TITLE
Match open source standards

### PR DESCRIPTION
**Pull request by evansolomon**
Hello @dpup, 

Please review the following commits I made in branch 'open-source-cleanup'.

0f3c10825de0d418d39bdb11d8bedbee39fced30 (2013-08-21 22:49:36 -0700)
Add copyright to files

7a6ccd532900484d1fbda31b13e7617fb27fdddf (2013-08-21 22:49:36 -0700)
Fill out/cleanup the package.json

b8ff07fd0ff560b7e356a940f366d9efa817815c (2013-08-21 22:49:36 -0700)
Spruce up Readme and use Apache license

R=@dpup

### CODE REVIEW

**Comment by dpup** [comment]
LGTM pending the other changes we talked about to make this a more general S3 utilities library.

/cc @vinibaggio since he wrote the S3Bucket tool in common.

**Comment by vinibaggio** [comment]
@evansolomon @dpup I had crazy problems with streams, so I reverted the S3Bucket to be read then write, which is unfortunately not the best. So, if we're going towards a more generic library, having the option to not use streams when possible it would be nice. I'm open to also talk about why it didn't work.

**Comment by evansolomon** [comment]
There's nothing that requires that everything we put in here use streams.  That said, I'm curious what problems you had because in general streams are pretty useful (imho).

**Comment by vinibaggio** [comment]
I agreed, I prefer streams as well. I will try to isolate the problem, but it seems that the write stream was never calling the 'finish' event and no error was raised. I couldn't figure out why though.

**Pull request merged**
