### PR TITLE
Changed the name from "s3 utils" to "canoe"

### PR DESCRIPTION
**Pull request by tessr**
Hello @evansolomon, 

Please review the following commits I made in branch 'tessr-summer-camp'.

aef4c7543479b690398da92a81482d19829c523c (2013-09-03 21:45:28 -0700)
Changed the name from "s3 utils" to "canoe"

R=@evansolomon

### CODE REVIEW

**Comment by evansolomon** [comment]
:shipit:

**Comment by dpup** [comment]
I like it.  You should claim the npm name asap :)

**Comment by evansolomon** [comment]
@dpup You can't claim the NPM name until you publish the module.  I think it's ready to go but we need a green light from @don-neufeld.

**Comment by dpup** [comment]
You can publish an empty branch.

**Comment by evansolomon** [comment]
I published the package.json + a sparse readme to get the NPM name.

https://npmjs.org/package/canoe

**Pull request merged**
